USE [master]
GO

/****** Object:  Database [carrental]    Script Date: 20.01.2023 12:07:30 ******/
CREATE DATABASE [carrental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'carrental', FILENAME = N'D:\SQLexpress\MSSQL15.SQLEXPRESS\MSSQL\DATA\carrental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'carrental_log', FILENAME = N'D:\SQLexpress\MSSQL15.SQLEXPRESS\MSSQL\DATA\carrental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [carrental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [carrental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [carrental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [carrental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [carrental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [carrental] SET ARITHABORT OFF 
GO

ALTER DATABASE [carrental] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [carrental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [carrental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [carrental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [carrental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [carrental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [carrental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [carrental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [carrental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [carrental] SET  ENABLE_BROKER 
GO

ALTER DATABASE [carrental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [carrental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [carrental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [carrental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [carrental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [carrental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [carrental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [carrental] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [carrental] SET  MULTI_USER 
GO

ALTER DATABASE [carrental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [carrental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [carrental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [carrental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [carrental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [carrental] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [carrental] SET QUERY_STORE = OFF
GO

ALTER DATABASE [carrental] SET  READ_WRITE 
GO


